/**
 * Stud Bridge Server — Web ↔ Roblox Studio plugin relay
 *
 * Roblox Studio can only make outgoing HTTP requests. This server queues
 * requests from the web app and delivers them to the plugin via polling.
 */

import express from "express";
import cors from "cors";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { createHash, randomBytes } from "node:crypto";

const __dirname = dirname(fileURLToPath(import.meta.url));
const TOKENS_FILE = join(__dirname, "studio-tokens.json");
import { DevelopmentConversationStore, MemoryConversationStore } from "./agent/store.ts";
import { AgentRuntime } from "./agent/runtime.ts";
import { RobloxStudioMcpGateway } from "./agent/tools.ts";
import { OpenCloudClient } from "./agent/open-cloud.ts";
import { createDataStoreTools } from "./agent/datastore-tools.ts";
import { createSubagentTool } from "./agent/subagent.ts";
import { createPlaytestTools } from "./agent/playtest-tools.ts";
import { createModelDriverFactory } from "./agent/drivers.ts";
import { createAgentRouter } from "./agent/routes.ts";
import { createMcpRequestHandler, buildMcpToolsList } from "./agent/mcp-server.ts";
import { PluginRelayTransport } from "./agent/studio-transport.ts";
import { runIngestion } from "./agent/corpus/ingest.ts";
import { corpusConfig } from "./agent/corpus/config.ts";
import { getPendingGames } from "./agent/corpus/postgres.ts";

try {
  process.loadEnvFile?.(".env");
} catch (error) {
  if (error.code !== "ENOENT") throw error;
}

const PORT = Number(process.env.PORT) || 3001;
const REQUEST_TIMEOUT_MS = 15_000;
const POLL_HOLD_MS = 500; // long-poll hold time; drops idle rate to ~1.7 req/s vs 10/s
const SESSION_ID_PATTERN = /^[A-Za-z0-9]{6,12}$/;

const app = express();
app.use(cors({ origin: true }));
app.use(express.json({ limit: "10mb" }));

/** @type {Map<string, { pending: Map<string, PendingRequest>, completed: Map<string, { result: unknown, completedAt: number }>, lastPoll: number, counter: number, pollWakeup: null | ((payload: unknown) => void), pluginVersion?: string, capabilities?: string[] }>} */
const sessions = new Map();

// --- Studio token auth ---
// Maps SHA-256(token) → { createdAt, sessionId }
const studioTokens = new Map();

const digestToken = (token) => createHash("sha256").update(token).digest("hex");
const newSessionId = () => randomBytes(6).toString("base64url").replace(/[^A-Za-z0-9]/g, "").slice(0, 8).toUpperCase();

/** Load persisted tokens from disk so server restarts don't break existing setups */
const loadTokens = () => {
  try {
    const data = JSON.parse(readFileSync(TOKENS_FILE, "utf8"));
    for (const [key, entry] of Object.entries(data)) {
      const hash = /^[a-f0-9]{64}$/i.test(key) ? key : digestToken(key);
      studioTokens.set(hash, entry);
    }
    if (studioTokens.size) console.log(`[Stud] Loaded ${studioTokens.size} studio token(s)`);
  } catch {
    // File doesn't exist yet — fine on first run
  }
};

const saveTokens = () => {
  writeFileSync(TOKENS_FILE, JSON.stringify(Object.fromEntries(studioTokens), null, 2));
};

loadTokens();

const bearer = (req) => {
  const header = req.header("authorization") || "";
  return header.startsWith("Bearer ") ? header.slice(7).trim() : "";
};

/** Extract and validate a Studio token.
 * Only accepts tokens that were explicitly generated by /auth/studio-token/generate.
 * Sends 401 and returns null on failure.
 */
const requireToken = (req, res) => {
  const token = (bearer(req) || req.header("X-Stud-Token") || "").trim();
  if (!token) {
    res.status(401).json({ error: "Missing Studio token" });
    return null;
  }
  const hash = digestToken(token);
  const entry = studioTokens.get(hash);
  if (!entry) {
    res.status(401).json({ error: "Token not recognised. Generate a new one at stud.com." });
    return null;
  }
  return { token, hash, entry };
};

/**
 * @typedef {{ tool: string, arguments?: Record<string, unknown>, operationId?: string, resolve: (r: unknown) => void, reject: (e: Error) => void, timer: ReturnType<typeof setTimeout>, createdAt: number }} PendingRequest
 */

const getSession = (sessionId) => {
  if (sessionId !== "default" && !SESSION_ID_PATTERN.test(sessionId)) return null;
  let session = sessions.get(sessionId);
  if (!session) {
    session = { pending: new Map(), completed: new Map(), lastPoll: 0, counter: 0, pollWakeup: null };
    sessions.set(sessionId, session);
  }
  return session;
};

const timestamp = () => Date.now();

// Window is POLL_HOLD_MS + generous buffer so long-polled sessions don't flap
const isStudioConnected = (session) => session.lastPoll > 0 && timestamp() - session.lastPoll < 3000;

const cleanupSession = (session) => {
  const now = timestamp();
  for (const [id, pending] of session.pending) {
    if (now - pending.createdAt > REQUEST_TIMEOUT_MS) {
      clearTimeout(pending.timer);
      pending.reject(new Error("Request timed out waiting for Studio response"));
      session.pending.delete(id);
    }
  }
  for (const [id, completed] of session.completed) {
    if (now - completed.completedAt > 5 * 60_000) session.completed.delete(id);
  }
};

const nextRequestId = (session) => {
  session.counter += 1;
  return `op_${session.counter}_${timestamp()}`;
};

const relayStudioRequest = (sessionId, tool, args, signal, operationId) => {
  const session = getSession(sessionId);
  if (!session) return Promise.reject(new Error("Invalid Studio session"));
  cleanupSession(session);
  if (!isStudioConnected(session)) {
    return Promise.reject(new Error("Roblox Studio is not connected. Open Studio and connect the Stud plugin."));
  }
  if (operationId && session.completed.has(operationId)) {
    return Promise.resolve(session.completed.get(operationId).result);
  }
  if (operationId && [...session.pending.values()].some((pending) => pending.operationId === operationId)) {
    return Promise.reject(new Error("Operation is already pending in Studio"));
  }
  const id = nextRequestId(session);
  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => {
      session.pending.delete(id);
      reject(new Error("Request timed out waiting for Studio response"));
    }, REQUEST_TIMEOUT_MS);
    session.pending.set(id, {
      tool,
      arguments: args ?? {},
      operationId: typeof operationId === "string" ? operationId : undefined,
      resolve,
      reject,
      timer,
      createdAt: timestamp(),
    });
    if (signal.aborted) {
      clearTimeout(timer);
      session.pending.delete(id);
      reject(new Error("Cancelled before Studio response"));
      return;
    }
    signal.addEventListener("abort", () => {
      const pending = session.pending.get(id);
      if (!pending) return;
      clearTimeout(pending.timer);
      session.pending.delete(id);
      reject(new Error("Cancelled before Studio response"));
    }, { once: true });
    if (session.pollWakeup) {
      const wakeup = session.pollWakeup;
      session.pollWakeup = null;
      wakeup({ id, tool, arguments: args ?? {} });
    }
  });
};

const pluginTransport = new PluginRelayTransport(relayStudioRequest);
const composedRelay = pluginTransport.toRelay();

const agentTools = new RobloxStudioMcpGateway(composedRelay);

// DataStore tools via Open Cloud. Approval is delegated to AgentRuntime, which
// emits a single `approval_pending` event per destructive mutation and waits
// for the React approval UI to resolve it.
const openCloudClient = new OpenCloudClient();
if (!openCloudClient.configured) {
  console.warn(
    "[Stud Bridge] Open Cloud DataStore tools are disabled. Set ROBLOX_OPEN_CLOUD_API_KEY and ROBLOX_UNIVERSE_ID in .env to enable.",
  );
}
const datastoreTools = createDataStoreTools(openCloudClient);

/**
 * Composite registry that combines studio gateway tools with DataStore tools.
 */
class CompositeToolRegistry {
  constructor(base, extra) {
    this._base = base;
    this._extra = extra;
  }

  list() {
    return [...this._base.list(), ...this._extra];
  }

  get(name) {
    return this._base.get(name) ?? this._extra.find((t) => t.name === name);
  }
}

const playtestTools = createPlaytestTools(composedRelay);
const combinedTools = new CompositeToolRegistry(agentTools, [...datastoreTools, ...playtestTools]);

// Subagent tool references combinedTools for read-only wrapping
const subagentTool = createSubagentTool(combinedTools);

class FinalToolRegistry {
  constructor(base, extra) {
    this._base = base;
    this._extra = extra;
  }

  list() {
    return [...this._base.list(), this._extra];
  }

  get(name) {
    return this._base.get(name) ?? (name === this._extra.name ? this._extra : undefined);
  }
}

const allTools = new FinalToolRegistry(combinedTools, subagentTool);

// Durable on-disk snapshot+JSONL conversation store. Tests opt back into
// MemoryConversationStore by setting STUD_AGENT_STORE=memory.
const conversationStore = process.env.STUD_AGENT_STORE === "memory"
  ? new MemoryConversationStore()
  : new DevelopmentConversationStore();
const agentRuntime = new AgentRuntime(
  conversationStore,
  createModelDriverFactory(allTools),
  allTools,
);
// Reconcile any runs that were "running" when a previous bridge process exited.
agentRuntime.recoverFromCrash()
  .then((ids) => { if (ids.length) console.log(`[agent] recovered ${ids.length} crashed conversation(s)`); })
  .catch((err) => console.error("[agent] crash recovery failed:", err));
app.use("/agent", createAgentRouter(agentRuntime));

// --- Cloud Studio routes (web + plugin) ---

const buildStudioStatus = (session) => {
  const pluginConnected = isStudioConnected(session);
  return {
    connected: pluginConnected,
    pluginConnected,
    mcpConnected: false,
    configuredTransport: "plugin",
    preferredTransport: "plugin_fallback",
    effectiveTransport: pluginConnected ? "plugin_fallback" : "unknown",
    lastUsedTransport: pluginTransport.lastUsed,
    mcpServer: null,
    mcpTools: [],
    mcpError: null,
    pending_requests: session.pending.size,
    last_poll_time: session.lastPoll ? timestamp() - session.lastPoll : null,
    pluginVersion: session.pluginVersion ?? null,
    capabilities: session.capabilities ?? [],
  };
};

// --- Studio token endpoints ---

/** Generate a new studio token. Pass { oldToken } in the body to revoke the previous one. */
app.post("/auth/studio-token/generate", (req, res) => {
  const oldToken = req.body?.oldToken;
  if (oldToken) studioTokens.delete(digestToken(String(oldToken)));
  const token = randomBytes(32).toString("base64url");
  const sessionId = newSessionId();
  studioTokens.set(digestToken(token), { createdAt: Date.now(), sessionId });
  saveTokens();
  res.json({ token, sessionId });
});

/** Revoke a token explicitly (called when user clears their token in the web app) */
app.post("/auth/studio-token/revoke", (req, res) => {
  const auth = requireToken(req, res);
  if (!auth) return;
  studioTokens.delete(auth.hash);
  saveTokens();
  res.json({ ok: true });
});

/** Validate a token and return studio connection status */
app.get("/auth/studio-token/validate", (req, res) => {
  const auth = requireToken(req, res);
  if (!auth) return;
  const { sessionId } = auth.entry;
  const session = sessions.get(sessionId);
  res.json({
    valid: true,
    sessionId,
    studioConnected: session ? isStudioConnected(session) : false,
  });
});

const handleStudioPoll = (req, res) => {
  const auth = requireToken(req, res);
  if (!auth) return;

  const { sessionId } = auth.entry;
  const session = getSession(sessionId);
  const pluginVersion = typeof req.query.pluginVersion === "string" ? req.query.pluginVersion : req.header("X-Stud-Plugin-Version");
  const capabilities = String(req.query.capabilities ?? req.header("X-Stud-Capabilities") ?? "")
    .split(",")
    .map((item) => item.trim())
    .filter(Boolean);
  session.lastPoll = timestamp();
  if (pluginVersion) session.pluginVersion = pluginVersion;
  if (capabilities.length) session.capabilities = capabilities;
  cleanupSession(session);

  const entry = session.pending.entries().next();
  if (!entry.done) {
    const [id, pending] = entry.value;
    res.json({ id, tool: pending.tool, arguments: pending.arguments ?? {} });
    return;
  }

  let settled = false;
  const settle = (payload) => {
    if (settled) return;
    settled = true;
    session.pollWakeup = null;
    if (!res.writableEnded) res.json(payload);
  };

  const timer = setTimeout(() => settle({ id: null }), POLL_HOLD_MS);
  session.pollWakeup = settle;
  req.on("close", () => {
    settled = true;
    clearTimeout(timer);
    session.pollWakeup = null;
  });
};

const handleStudioRespond = (req, res) => {
  const auth = requireToken(req, res);
  if (!auth) return;

  const { sessionId } = auth.entry;
  const session = getSession(sessionId);

  const { id, result, isError, error } = req.body;
  if (!id) {
    res.status(400).json({ error: "Missing id" });
    return;
  }

  const pending = session.pending.get(id);
  if (!pending) {
    res.json({ error: "Request not found" });
    return;
  }

  clearTimeout(pending.timer);
  session.pending.delete(id);
  const output = isError ? { error: error || "Studio tool failed" } : result;
  if (pending.operationId) session.completed.set(pending.operationId, { result: output, completedAt: timestamp() });
  pending.resolve(output);
  res.json({ ok: true });
};

app.post("/studio/request", async (req, res) => {
  const auth = requireToken(req, res);
  if (!auth) return;
  const tool = String(req.body?.tool ?? "");
  if (!tool) {
    res.status(400).json({ error: "Missing tool" });
    return;
  }
  const controller = new AbortController();
  try {
    const result = await composedRelay(
      auth.entry.sessionId,
      tool,
      req.body?.arguments && typeof req.body.arguments === "object" ? req.body.arguments : {},
      controller.signal,
      `direct_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`,
    );
    res.json(result);
  } catch (error) {
    res.status(500).json({ error: error instanceof Error ? error.message : String(error) });
  }
});

app.get("/studio/poll", handleStudioPoll);
app.post("/studio/respond", handleStudioRespond);
app.get("/stud/token/poll", handleStudioPoll);
app.post("/stud/token/respond", handleStudioRespond);

/** Token-based status — web app polls this to see if Studio is connected */
const handleStudioStatus = (req, res) => {
  const auth = requireToken(req, res);
  if (!auth) return;

  const { sessionId } = auth.entry;
  const session = getSession(sessionId);
  cleanupSession(session);
  res.json(buildStudioStatus(session));
};

app.get("/studio/status", handleStudioStatus);
app.get("/stud/token/status", handleStudioStatus);

const mcpHandler = createMcpRequestHandler(allTools, composedRelay);

app.get("/mcp/info", (_req, res) => {
  res.json({
    name: "Stud",
    description: "Cloud MCP server for Roblox Studio",
    tools: buildMcpToolsList(allTools).map((tool) => tool.name),
  });
});

app.get("/mcp", (req, res) => {
  const auth = requireToken(req, res);
  if (!auth) return;
  res.setHeader("Content-Type", "text/event-stream");
  res.setHeader("Cache-Control", "no-cache");
  res.setHeader("Connection", "keep-alive");
  res.flushHeaders();
  res.write(`data: ${JSON.stringify({ type: "endpoint", uri: "/mcp" })}\n\n`);
  const keepAlive = setInterval(() => res.write(": keep-alive\n\n"), 15_000);
  req.on("close", () => clearInterval(keepAlive));
});

app.post("/mcp", async (req, res) => {
  const auth = requireToken(req, res);
  if (!auth) return;
  await mcpHandler(req, res, auth.entry.sessionId);
});

// --- Whitelisted fetch proxy (Roblox catalog, models.dev, etc.) ---

const PROXY_ALLOWED = [
  "https://catalog.roblox.com/",
  "https://thumbnails.roblox.com/",
  "https://apis.roblox.com/",
];

app.get("/api/proxy", async (req, res) => {
  const target = String(req.query.url || "");
  const allowed = PROXY_ALLOWED.some((prefix) => target.startsWith(prefix));
  if (!allowed) {
    res.status(403).json({ error: "URL not allowed" });
    return;
  }

  try {
    const upstream = await fetch(target, {
      headers: {
        Accept: "application/json",
        "User-Agent": "Stud/1.0",
      },
    });
    const text = await upstream.text();
    res.status(upstream.status).type(upstream.headers.get("content-type") || "application/json").send(text);
  } catch (e) {
    res.status(502).json({ error: String(e) });
  }
});

// --- Corpus ---

app.get("/corpus/status", async (_req, res) => {
  if (!corpusConfig.enabled) return res.json({ enabled: false });
  if (!corpusConfig.ready) return res.json({ enabled: true, ready: false, missing: corpusConfig.missing });
  try {
    const pending = await getPendingGames();
    res.json({ enabled: true, ready: true, pendingGames: pending.length, pending: pending.map((g) => g.slug) });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.post("/corpus/ingest", async (_req, res) => {
  if (!corpusConfig.ready) {
    return res.status(400).json({ error: "Corpus not ready", missing: corpusConfig.missing });
  }
  try {
    const report = await runIngestion(corpusConfig);
    res.json(report);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.post("/corpus/games", async (req, res) => {
  const { slug, name, niche, r2Prefix, qualityScore } = req.body ?? {};
  if (!slug || !name || !niche || !r2Prefix) {
    return res.status(400).json({ error: "slug, name, niche, r2Prefix are required" });
  }
  if (!corpusConfig.ready) {
    return res.status(400).json({ error: "Corpus not ready", missing: corpusConfig.missing });
  }
  try {
    const { getPrismaClient } = await import("./agent/corpus/postgres.ts");
    const prisma = getPrismaClient();
    const game = await prisma.game.upsert({
      where: { slug },
      update: { name, niche, r2Prefix, qualityScore: qualityScore ?? 0.7 },
      create: { slug, name, niche, r2Prefix, qualityScore: qualityScore ?? 0.7, ingested: false },
    });
    res.json({ ok: true, game });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// --- Health ---

app.get("/health", (_req, res) => {
  res.json({ ok: true, sessions: sessions.size });
});


app.listen(PORT, () => {
  console.log(`[Stud Bridge] http://localhost:${PORT}`);
  console.log("[Stud Bridge] Waiting for web app and Studio plugin...");
});
